server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: "flask-app"
          __path__: /var/lib/docker/containers/*/*-json.log